name: 'Trigger CircleCI Pipeline'
description: 'Trigger pipelines on CircleCI for any event on GitHub.'
branding:
    icon: "check-circle"
    color: "green"
inputs:
  GHA_Meta:
    required: false
    description: 'An optional additional metadata parameter. Will be available on the CircleCI pipeline as GHA_Meta'
  GHA_Data:
    required: false
    description: 'A parameter for passing payload data. Will be available on the CircleCI pipeline as GHA_Data'
  CCI_Context:
    required: false
    description: 'An optional CircleCI context to use when running jobs. Will be available on the CircleCI pipeline as CCI_Context'
  Follow:
    default: false
    description: 'Follow the progress of the CircleCI pipeline and report success or failure based on pipeline success/failure.'
outputs:
  id:
    description: The unique ID of the pipeline.
  state:
    description: The current state of the pipeline.
  number:
    description: The number of the pipeline.
  created_at:
    description: The date and time the pipeline was created.
runs:
  using: 'node12'
  main: 'dist/index.js'
